version: '3'
services:
  nginx:
    build: nginx/
    command: sh -c 'nginx -g "daemon off;"'
    depends_on:
      - app
    links:
      - app
    ports:
      - "8080:80"
  app:
    build: app/
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app/blog:/srv
    working_dir: /srv
    command: >
      bash -c 'mix deps.get &&
      mix ecto.create &&
      mix ecto.migrate &&
      cd assets && npm install &&
      cd .. &&
      mix phx.server'
    expose:
      - "4000"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
